---
title: "LinearModel_CodingNotes"
output: html_document
---

Introduction to Regression Analysis in R
Loading libraries
```{r}
library(tidyverse)
library(lme4)
library(emmeans)
library(multcomp)
library(ggplot2)
library(multcompView)
```

Continuous X and Continuous Y

```{r}
#Loading the data
data("mtcars")
```


```{r}
#plotting the data
ggplot(mtcars, aes(x = wt, y = mpg)) +
  geom_smooth(method = lm, se = FALSE, color = "grey") +
  geom_point(aes(color = wt)) +
  xlab("Weight") + 
  ylab("Miles per gallon") +
  scale_colour_gradient(low = "forestgreen", high = "black") +
  theme_classic()
```


```{r}
# Linear regression
lm1 = lm(mpg~wt, data = mtcars)
lm1
```


```{r}
#Checking the summary of the linear model
summary(lm1)
```


```{r}
#anova calculation
anova(lm1)
```


```{r}
#Correlation test
cor.test(mtcars$wt, mtcars$mpg)
```

Categorical variables

```{r}
#Loading the fungicide data
bull.rich <- read.csv("Bull_richness.csv")
```


```{r}
#Filter our dataset to include one treatment and growth stage 
bull.rich %>%
  filter(GrowthStage == "V8" & Treatment == "Conv.") %>%
  ggplot(aes(x = Fungicide, y = richness)) + 
  geom_boxplot()
```


```{r}
# t-test
bull.rich.sub <- bull.rich %>%
  filter(GrowthStage == "V8" & Treatment == "Conv.")

t.test(richness~Fungicide, data = bull.rich.sub)
```


```{r}
summary(lm(richness~Fungicide, data = bull.rich.sub))
anova(lm(richness~Fungicide, data = bull.rich.sub))
```

ANOVAS

```{r}
bull.rich.sub2 <- bull.rich %>%
  filter(Fungicide == "C" & Treatment == "Conv." & Crop == "Corn")
```


```{r}
bull.rich.sub2$GrowthStage <- factor(bull.rich.sub2$GrowthStage, levels = c("V6", "V8", "V15"))

ggplot(bull.rich.sub2, aes(x = GrowthStage, y = richness)) +
  geom_boxplot()
```


```{r}
lm.growth <- lm(richness ~ GrowthStage, data = bull.rich.sub2)
summary(lm.growth)
```


```{r}
anova(lm.growth)
```


```{r}
summary(aov(richness ~ GrowthStage, data = bull.rich.sub2))
```


```{r}
lsmeans <- emmeans(lm.growth, ~GrowthStage)
Results_lsmeans <- cld(lsmeans, alpha = 0.05, reversed = TRUE, details = TRUE)
Results_lsmeans
```


Interaction terms

```{r}
bull.rich.sub3 <- bull.rich %>%
  filter(Treatment == "Conv." & Crop == "Corn")

bull.rich.sub3$GrowthStage <- factor(bull.rich.sub3$GrowthStage, levels = c("V6", "V8", "V15"))
```


```{r}
lm.inter <- lm(richness ~ GrowthStage + Fungicide + GrowthStage:Fungicide, data = bull.rich.sub3)

# or like this
lm(richness ~ GrowthStage*Fungicide, data = bull.rich.sub3)
```


```{r}
summary(lm.inter) # significant terms
```


```{r}
anova(lm.inter) # The interaction term is signifant. 
```


```{r}
lsmeans <- emmeans(lm.inter, ~Fungicide|GrowthStage)
Results_lsmeans <- cld(lsmeans, alpha = 0.05, reversed = TRUE, details = TRUE) 
Results_lsmeans
```


```{r}
bull.rich.sub3 %>%
  ggplot(aes(x = GrowthStage, y = richness, fill = Fungicide)) +
  geom_boxplot()
```


Mizec effects models
```{r}
lme0 <- lm(richness ~ GrowthStage*Fungicide, data = bull.rich.sub3)
```


```{r}
lme1 <- lmer(richness ~ GrowthStage*Fungicide + (1|Rep), data = bull.rich.sub3)
```


```{r}
summary(lme0)
summary(lme1)
```


